/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basketballscoreboard;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.Timer;

public final class BasketBall extends javax.swing.JFrame{

    /**
     * Creates new form BasketBall
     */
    
    int period = 0;
    int homeScore = 0;
    int guestScore = 0;
    int homeFouls = 0;
    int guestFouls = 0;
    
    long shotClock = 24000;
    long lastUpdate;
    Timer shotClockTimer;
    
    long periodTime = 600000;
    long periodUpdate;
    Timer periodTimer;
    
    boolean screset = false;
    boolean preset = false;
    boolean supsended = false;
    
    Runnable r, sc;
    Thread t, st;
    
    public BasketBall() {
        this.setTitle("Basketball Scoreboard");
        ImageIcon icon =  new ImageIcon(this.getClass().getResource("basketball.png"));
        this.setIconImage(icon.getImage());
        initComponents();
        shotClock();
        periodClock();  
    }
    
    public void shotClock(){
        sc = () -> {
            int s = 24;
            int ms = 0;
            while (s>=0){
                ShotClock.setText(String.format("%02d", s)+"."+String.format("%03d", ms));
                try {
                    ms--;
                    if(ms<0){
                        ms = 999;
                        s--;
                    }
                    if(s<10){
                        ShotClock.setForeground(Color.ORANGE);
                    }
                    if(s<0){
                        t.suspend();
                        supsended = true;
                        ShotClock.setForeground(Color.decode("#FF3333"));
                    }
                    Thread.sleep(1L);
                }
                catch (InterruptedException e) {    
                    System.out.println("Error");
                }
            }
        };
        st = new Thread(sc);
    }
    
    public void periodClock(){
        r = () -> {
            int min = 10;
            int s = 0;
            int ms = 0;
            while (min>0){
                Timer.setText(String.format("%02d", min)+":"+String.format("%02d", s)+"."+String.format("%03d", ms));
                try {
                    ms--;
                    if(ms<0){
                        ms = 999;
                        s--;
                    }
                    if(s<0){
                        s = 59;
                        min--;
                    }
                    Thread.sleep(1L);
                }
                catch (InterruptedException e) {    
                    System.out.println("Error");
                }
            }
        };
        t = new Thread(r);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScoreBoardPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        HomeLabel = new javax.swing.JLabel();
        MinusHome = new javax.swing.JButton();
        AddHome = new javax.swing.JButton();
        GuestPanel = new javax.swing.JPanel();
        Guest = new javax.swing.JLabel();
        GuestLabel = new javax.swing.JLabel();
        MinusGuest = new javax.swing.JButton();
        AddGuest = new javax.swing.JButton();
        HomeFoulPanel = new javax.swing.JPanel();
        HomeFoul = new javax.swing.JLabel();
        HomeFoulLabel = new javax.swing.JLabel();
        AddHomeFoul = new javax.swing.JButton();
        MinusHomeFoul = new javax.swing.JButton();
        GuestFoulPanel = new javax.swing.JPanel();
        GuestFoul = new javax.swing.JLabel();
        GuestFoulLabel = new javax.swing.JLabel();
        AddGuestFoul = new javax.swing.JButton();
        MinusGuestFoul = new javax.swing.JButton();
        PeriodPanel = new javax.swing.JPanel();
        PeriodLabel = new javax.swing.JLabel();
        Period = new javax.swing.JLabel();
        AddPeriod = new javax.swing.JButton();
        MinusPeriod = new javax.swing.JButton();
        TimePanel = new javax.swing.JPanel();
        TimerLabel = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        TimerReset = new javax.swing.JButton();
        ShotClockPanel = new javax.swing.JPanel();
        ShotClockLabel = new javax.swing.JLabel();
        ShotClock = new javax.swing.JLabel();
        SCResume = new javax.swing.JButton();
        SCStop = new javax.swing.JButton();
        SCReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ScoreBoardPanel.setBackground(new java.awt.Color(0, 0, 0));

        HomePanel.setBackground(new java.awt.Color(0, 0, 0));

        Home.setFont(new java.awt.Font("Dialog", 0, 150)); // NOI18N
        Home.setForeground(new java.awt.Color(230, 180, 51));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setText("0");
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        HomeLabel.setBackground(new java.awt.Color(0, 0, 0));
        HomeLabel.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("HOME");

        MinusHome.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        MinusHome.setText("↓");
        MinusHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusHomeMouseClicked(evt);
            }
        });

        AddHome.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AddHome.setText("↑");
        AddHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(MinusHome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(AddHome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HomeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MinusHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddHome, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        GuestPanel.setBackground(new java.awt.Color(0, 0, 0));
        GuestPanel.setForeground(new java.awt.Color(255, 255, 255));

        Guest.setFont(new java.awt.Font("Dialog", 0, 150)); // NOI18N
        Guest.setForeground(new java.awt.Color(230, 180, 51));
        Guest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Guest.setText("0");
        Guest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        GuestLabel.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        GuestLabel.setForeground(new java.awt.Color(255, 255, 255));
        GuestLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuestLabel.setText("GUEST");

        MinusGuest.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        MinusGuest.setText("↓");
        MinusGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusGuestMouseClicked(evt);
            }
        });

        AddGuest.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AddGuest.setText("↑");
        AddGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddGuestMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GuestPanelLayout = new javax.swing.GroupLayout(GuestPanel);
        GuestPanel.setLayout(GuestPanelLayout);
        GuestPanelLayout.setHorizontalGroup(
            GuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(GuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Guest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GuestPanelLayout.createSequentialGroup()
                        .addComponent(MinusGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(AddGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GuestLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        GuestPanelLayout.setVerticalGroup(
            GuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuestPanelLayout.createSequentialGroup()
                .addComponent(GuestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Guest, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MinusGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(AddGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        HomeFoulPanel.setBackground(new java.awt.Color(0, 0, 0));
        HomeFoulPanel.setForeground(new java.awt.Color(255, 255, 255));

        HomeFoul.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        HomeFoul.setForeground(new java.awt.Color(230, 180, 51));
        HomeFoul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeFoul.setText("0");
        HomeFoul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        HomeFoulLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        HomeFoulLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeFoulLabel.setText("FOULS");

        AddHomeFoul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AddHomeFoul.setText("↑");
        AddHomeFoul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddHomeFoulMouseClicked(evt);
            }
        });

        MinusHomeFoul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        MinusHomeFoul.setText("↓");
        MinusHomeFoul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusHomeFoulMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomeFoulPanelLayout = new javax.swing.GroupLayout(HomeFoulPanel);
        HomeFoulPanel.setLayout(HomeFoulPanelLayout);
        HomeFoulPanelLayout.setHorizontalGroup(
            HomeFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeFoulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinusHomeFoul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HomeFoulPanelLayout.createSequentialGroup()
                        .addComponent(HomeFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AddHomeFoul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeFoulPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(HomeFoulLabel)))
                .addContainerGap())
        );
        HomeFoulPanelLayout.setVerticalGroup(
            HomeFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeFoulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeFoulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddHomeFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinusHomeFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GuestFoulPanel.setBackground(new java.awt.Color(0, 0, 0));
        GuestFoulPanel.setForeground(new java.awt.Color(255, 255, 255));

        GuestFoul.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        GuestFoul.setForeground(new java.awt.Color(230, 180, 51));
        GuestFoul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuestFoul.setText("0");
        GuestFoul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        GuestFoulLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        GuestFoulLabel.setForeground(new java.awt.Color(255, 255, 255));
        GuestFoulLabel.setText("FOULS");

        AddGuestFoul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AddGuestFoul.setText("↑");
        AddGuestFoul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddGuestFoulMouseClicked(evt);
            }
        });

        MinusGuestFoul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        MinusGuestFoul.setText("↓");
        MinusGuestFoul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusGuestFoulMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GuestFoulPanelLayout = new javax.swing.GroupLayout(GuestFoulPanel);
        GuestFoulPanel.setLayout(GuestFoulPanelLayout);
        GuestFoulPanelLayout.setHorizontalGroup(
            GuestFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestFoulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuestFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinusGuestFoul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddGuestFoul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GuestFoulPanelLayout.createSequentialGroup()
                        .addGroup(GuestFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuestFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuestFoulLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GuestFoulPanelLayout.setVerticalGroup(
            GuestFoulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuestFoulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuestFoulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuestFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddGuestFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinusGuestFoul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PeriodPanel.setBackground(new java.awt.Color(0, 0, 0));
        PeriodPanel.setForeground(new java.awt.Color(255, 255, 255));

        PeriodLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        PeriodLabel.setForeground(new java.awt.Color(255, 255, 255));
        PeriodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PeriodLabel.setText("Period");

        Period.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        Period.setForeground(new java.awt.Color(255, 51, 51));
        Period.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Period.setText("1");
        Period.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        AddPeriod.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AddPeriod.setText("↑");
        AddPeriod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPeriodMouseClicked(evt);
            }
        });

        MinusPeriod.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        MinusPeriod.setText("↓");
        MinusPeriod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusPeriodMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PeriodPanelLayout = new javax.swing.GroupLayout(PeriodPanel);
        PeriodPanel.setLayout(PeriodPanelLayout);
        PeriodPanelLayout.setHorizontalGroup(
            PeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeriodPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PeriodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Period, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinusPeriod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PeriodPanelLayout.setVerticalGroup(
            PeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeriodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PeriodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Period, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinusPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TimePanel.setBackground(new java.awt.Color(0, 0, 0));
        TimePanel.setForeground(new java.awt.Color(255, 255, 255));

        TimerLabel.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        TimerLabel.setForeground(new java.awt.Color(255, 255, 255));
        TimerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimerLabel.setText("TIME");

        Timer.setBackground(new java.awt.Color(255, 255, 255));
        Timer.setFont(new java.awt.Font("Dialog", 0, 120)); // NOI18N
        Timer.setForeground(new java.awt.Color(255, 51, 51));
        Timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Timer.setText("10:00.000");
        Timer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TimerReset.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        TimerReset.setText("RESET");
        TimerReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimerResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimerReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addComponent(TimerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TimerReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ShotClockPanel.setBackground(new java.awt.Color(0, 0, 0));
        ShotClockPanel.setForeground(new java.awt.Color(255, 255, 255));

        ShotClockLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ShotClockLabel.setForeground(new java.awt.Color(255, 255, 255));
        ShotClockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShotClockLabel.setText("Shot Clock");

        ShotClock.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        ShotClock.setForeground(new java.awt.Color(0, 255, 102));
        ShotClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShotClock.setText("24.000");
        ShotClock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        SCResume.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SCResume.setText("START");
        SCResume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCResumeMouseClicked(evt);
            }
        });

        SCStop.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SCStop.setText("STOP");
        SCStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCStopMouseClicked(evt);
            }
        });

        SCReset.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SCReset.setText("RESET");
        SCReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ShotClockPanelLayout = new javax.swing.GroupLayout(ShotClockPanel);
        ShotClockPanel.setLayout(ShotClockPanelLayout);
        ShotClockPanelLayout.setHorizontalGroup(
            ShotClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShotClockPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(ShotClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShotClockPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(ShotClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(ShotClockPanelLayout.createSequentialGroup()
                        .addGroup(ShotClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ShotClock, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ShotClockPanelLayout.createSequentialGroup()
                                .addComponent(SCReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SCStop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SCResume, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ShotClockPanelLayout.setVerticalGroup(
            ShotClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShotClockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShotClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShotClock, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ShotClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SCStop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCResume, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ScoreBoardPanelLayout = new javax.swing.GroupLayout(ScoreBoardPanel);
        ScoreBoardPanel.setLayout(ScoreBoardPanelLayout);
        ScoreBoardPanelLayout.setHorizontalGroup(
            ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreBoardPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ScoreBoardPanelLayout.createSequentialGroup()
                        .addComponent(HomeFoulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuestFoulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ScoreBoardPanelLayout.createSequentialGroup()
                        .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(PeriodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(GuestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScoreBoardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShotClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ScoreBoardPanelLayout.setVerticalGroup(
            ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreBoardPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HomeFoulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuestFoulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ShotClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScoreBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScoreBoardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddHomeFoulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddHomeFoulMouseClicked
        if(homeFouls < 99){
            homeFouls = homeFouls+1;
            HomeFoul.setText(""+homeFouls);   
        }
    }//GEN-LAST:event_AddHomeFoulMouseClicked

    private void MinusHomeFoulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusHomeFoulMouseClicked
        if(homeFouls > 0){
            homeFouls = homeFouls-1;
            HomeFoul.setText(""+homeFouls);   
        }
    }//GEN-LAST:event_MinusHomeFoulMouseClicked

    private void AddGuestFoulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddGuestFoulMouseClicked
        if(guestFouls < 99){
            guestFouls = guestFouls+1;
            GuestFoul.setText(""+guestFouls);   
        }
    }//GEN-LAST:event_AddGuestFoulMouseClicked

    private void MinusGuestFoulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusGuestFoulMouseClicked
        if(guestFouls > 0){
            guestFouls = guestFouls-1;
            GuestFoul.setText(""+guestFouls);   
        }
    }//GEN-LAST:event_MinusGuestFoulMouseClicked

    private void AddHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddHomeMouseClicked
        if(homeScore < 999){
            homeScore = homeScore+1;
            Home.setText(""+homeScore);   
        }
    }//GEN-LAST:event_AddHomeMouseClicked

    private void MinusHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusHomeMouseClicked
        if(homeScore > 0){
            homeScore = homeScore-1;
            Home.setText(""+homeScore);   
        }
    }//GEN-LAST:event_MinusHomeMouseClicked

    private void AddGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddGuestMouseClicked
        if(guestScore < 999){
            guestScore = guestScore+1;
            Guest.setText(""+guestScore);   
        }
    }//GEN-LAST:event_AddGuestMouseClicked

    private void MinusGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusGuestMouseClicked
        if(guestScore > 0){
            guestScore = guestScore-1;
            Guest.setText(""+guestScore);   
        }
    }//GEN-LAST:event_MinusGuestMouseClicked

    private void AddPeriodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPeriodMouseClicked
        if(period < 4){
            period = period+1;
            Period.setText(""+period);   
        }
    }//GEN-LAST:event_AddPeriodMouseClicked

    private void MinusPeriodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusPeriodMouseClicked
        if(period > 1){
            period = period-1;
            Period.setText(""+period);    
        }
    }//GEN-LAST:event_MinusPeriodMouseClicked

    private void SCResumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCResumeMouseClicked
        if(supsended){
            t.resume();
            st.resume();
            supsended = false;
        }else{
            if(screset && preset){
                t.start();
               st.start();
               supsended = false;
               preset = false;
               screset = false;
            }else if(screset){
                t.resume();
                st.start();
                supsended = false;
                screset = false;
            }else if(preset){
                st.resume();
                t.start();
                supsended = false;
                preset = false;                
            }else{
               t.start();
               st.start();
               supsended = false;
            }
        }
    }//GEN-LAST:event_SCResumeMouseClicked

    private void SCStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCStopMouseClicked
        if(!supsended){
            t.suspend();
            st.suspend();
            supsended = true;
        }
    }//GEN-LAST:event_SCStopMouseClicked

    private void SCResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCResetMouseClicked
        if(supsended){
            shotClock();
            ShotClock.setText("24.000");
            ShotClock.setForeground(Color.decode("#00FF66"));
            supsended = false;
            screset = true;
        }
    }//GEN-LAST:event_SCResetMouseClicked

    private void TimerResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimerResetMouseClicked
        if(supsended){
            periodClock();
            Timer.setText("10:00.000");
            supsended = false;
            preset = true;
        } 
    }//GEN-LAST:event_TimerResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasketBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasketBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasketBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasketBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BasketBall().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddGuest;
    private javax.swing.JButton AddGuestFoul;
    private javax.swing.JButton AddHome;
    private javax.swing.JButton AddHomeFoul;
    private javax.swing.JButton AddPeriod;
    private javax.swing.JLabel Guest;
    private javax.swing.JLabel GuestFoul;
    private javax.swing.JLabel GuestFoulLabel;
    private javax.swing.JPanel GuestFoulPanel;
    private javax.swing.JLabel GuestLabel;
    private javax.swing.JPanel GuestPanel;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel HomeFoul;
    private javax.swing.JLabel HomeFoulLabel;
    private javax.swing.JPanel HomeFoulPanel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton MinusGuest;
    private javax.swing.JButton MinusGuestFoul;
    private javax.swing.JButton MinusHome;
    private javax.swing.JButton MinusHomeFoul;
    private javax.swing.JButton MinusPeriod;
    private javax.swing.JLabel Period;
    private javax.swing.JLabel PeriodLabel;
    private javax.swing.JPanel PeriodPanel;
    private javax.swing.JButton SCReset;
    private javax.swing.JButton SCResume;
    private javax.swing.JButton SCStop;
    private javax.swing.JPanel ScoreBoardPanel;
    private javax.swing.JLabel ShotClock;
    private javax.swing.JLabel ShotClockLabel;
    private javax.swing.JPanel ShotClockPanel;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel TimerLabel;
    private javax.swing.JButton TimerReset;
    // End of variables declaration//GEN-END:variables
}
